app/models/booking.rb
app/models/listing.rb
app/models/user.rb
db/migrate/20200224153102_create_bookings.rb
db/schema.rb
test/models/booking_test.rb

added the bookings model with validations and relationships

Bookings model

---

app/controllers/listings_controller.rb
config/routes.rb
test/controllers/listings_controller_test.rb

added the index method and controller action to the listings controller

Index listings

---

Gemfile
app/assets/stylesheets/pages/_home.scss
app/views/pages/home.html.erb

adding form

---

app/models/listing.rb
db/migrate/20200224165357_add_name_to_listings.rb
db/migrate/20200224165403_add_start_date_to_listings.rb
db/migrate/20200224165408_add_end_date_to_listings.rb
db/schema.rb

added name as well as start and end date field to the listings model

Add to listing

---

app/assets/stylesheets/pages/_home.scss
app/views/pages/home.html.erb

Hey guys,
Added CSS styling for the background image to the CSS stylesheet.
Thanks,
P

Changes made to the CSS file

---

app/assets/stylesheets/pages/_home.scss
app/views/layouts/application.html.erb
app/views/pages/home.html.erb

adding js for the dating , the code to be order

Frontend 3

---

app/assets/stylesheets/pages/_home.scss
app/views/components/_form_homepage.html.erb
app/views/pages/home.html.erb

Just shortened the code for view file

Backend index

---

app/controllers/listings_controller.rb

Added index, show, new and create methods to the controller

Listings controller done

---

app/controllers/listings_controller.rb
db/migrate/20200225114406_add_prices_to_listings.rb
db/schema.rb

Dedicated to you mate, Bjarne!!

Prices column added to the database and if condition for empty search

---

app/views/components/_form_homepage.html.erb
app/views/listings/index.html.erb
db/seeds.rb

Hey guys,
Please use db:seed to get the updated database of vehicles.
Thanks,
P

Seeds file updated, index file updated, search form works

---

app/assets/config/manifest.js
app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_custom-typo.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/components/_search-form.scss
app/assets/stylesheets/pages/_index.scss
app/views/components/_form_homepage.html.erb

1. form fixed (almost :)
2. Form is now responsive (using Bootstraps col-mg, col-lg....etc)
3.  scss files organized and cleaner
4. created a _custom_typo.scss where we can put our custom typographic elements, like letter-spacing and other typographic stuff. 
WHAT IS STILL MISSING
- Form Buttons names
- Form left align in big screens

form fixed, missing btn names and left-indentation

---

app/assets/stylesheets/components/_custom-typo.scss
app/assets/stylesheets/components/_search-form.scss
app/views/components/_form_homepage.html.erb

Form is finished: 
1. Buttons names added
2. Indentation Left done
:)

Form homepage fix

---

app/assets/config/manifest.js
app/views/components/_form_homepage.html.erb
app/views/devise/confirmations/new.html.erb
app/views/devise/mailer/confirmation_instructions.html.erb
app/views/devise/mailer/email_changed.html.erb
app/views/devise/mailer/password_change.html.erb
app/views/devise/mailer/reset_password_instructions.html.erb
app/views/devise/mailer/unlock_instructions.html.erb
app/views/devise/passwords/edit.html.erb
app/views/devise/passwords/new.html.erb
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/devise/shared/_error_messages.html.erb
app/views/devise/shared/_links.html.erb
app/views/devise/unlocks/new.html.erb
app/views/layouts/application.html.erb
config/routes.rb

Signup views

---

app/assets/stylesheets/components/_search-form.scss
app/views/components/_form_homepage.html.erb

Search Form redone and working

New search

---

app/assets/stylesheets/components/_slides.scss
app/controllers/listings_controller.rb
app/views/listings/show.html.erb

adding 2 buttoms to show page
enjoy :)

Frontend 100

---

app/assets/stylesheets/components/_listing-card.scss
app/views/listings/index.html.erb

Fixed the raise issue
Thanks,
P

Index page

---

app/controllers/listings_controller.rb
app/controllers/users_controller.rb
app/views/users/show.html.erb

Profile page complete
Thanks,
P

Simple profile page done

---

app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/config/_fonts.scss
app/views/components/_navbar.html.erb

new logo added

---

app/assets/stylesheets/components/_custom-typo.scss
app/views/listings/show.html.erb

- Typographic fixed, now look nicer
- btn height problem solved

New show page

---

app/views/components/_listing-card.html.erb
app/views/listings/index.html.erb

dark bg added to index page

---

app/assets/stylesheets/components/_colors.scss
app/assets/stylesheets/components/_custom-typo.scss
app/views/components/_booking-card.html.erb
app/views/listings/show.html.erb

booking card finished

---

app/controllers/bookings_controller.rb
app/views/components/_booking-card.html.erb
app/views/users/show.html.erb

Changes made to the booking and profile page

changes made to the profile-page

---

app/controllers/bookings_controller.rb
app/javascript/packs/application.js
app/views/bookings/new.html.erb
app/views/components/_booking-card.html.erb
app/views/components/_listing-card.html.erb
db/schema.rb

Changes to the total price :)
DEDICATED TO LUIS!!

Changes made to the total price of the booking

---

app/views/bookings/new.html.erb
db/schema.rb

Layout and current_user actualised

Booking page

---

app/views/components/_form_homepage.html.erb

Some explanatory text at the search form

added text to search form
